/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DownloadID */

#ifndef _Included_DownloadID
#define _Included_DownloadID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DownloadID
 * Method:    MAC_to_DownloadID
 * Signature: ([C[C)I
 */
JNIEXPORT jint JNICALL Java_DownloadID_MAC_1to_1DownloadID
  (JNIEnv *, jobject, jcharArray, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
